### ISSUE TITLE
Doesn't parse log messages where the connection was closed

### ISSUE THREAD

**Issue by fredrik** [tobyhs/haproxy_log_parser#2]
This log line raises `HAProxyLogParser::ParseError`:

`Jan 23 06:35:46 localhost haproxy[15887]: 1.1.1.1:40217 [23/Jan/2017:06:35:46.641] fe_edge/2: Connection closed during SSL handshake`

(The IP address has been changed to 1.1.1.1).

Is this intended behaviour?

**Comment by tobyhs** [comment]
Hi @fredrik 

I didn't consider connection error lines when initially writing this. I'm thinking about what the interface could be when encountering such lines, and am considering one of the following:
1) have `HAProxyLogParser.parse` return an object of a different type from `Entry`
2) have `HAProxyLogParser.parse`raise an error (that isn't `ParseError`)

Do you have any thoughts or preferences?

**Comment by fredrik** [comment]
I'm thinking the first of the two options is preferable since that would potentially let me access attributes such as timestamp, client IP and edge name. Useful for counting things!

Could it be problematic for users if `parse` returns a different type of object in this case? If the objects returned behave the same ("quack!") it's fine I suppose, but that could require checking for either the type returned or the presence of some attribute that you are interested in. Tricky.

**Comment by tobyhs** [comment]
Hi @fredrik 

I implemented option 1 in https://github.com/tobyhs/haproxy_log_parser/pull/3 ; let me know if you have any thoughts.

**Comment by fredrik** [comment]
Looking good!

If I were to count the number of errors in my logs, or if I only wanted to include successful requests for some reason, how would I go about that? Perhaps the entry classes ought to have a `success` attribute?

**Comment by tobyhs** [comment]
If you want to only include successful requests, I think you can have something like an `if result.is_a?(HAProxyLogParser::Entry)` check.

**Comment by fredrik** [comment]
Fair enough 👍

**Comment by tobyhs** [comment]
I'll release a new version within the next few days.

**Comment by tobyhs** [comment]
@fredrik I just released https://rubygems.org/gems/haproxy_log_parser/versions/2.0.0. Feel free to reopen this issue if it isn't working as expected.
